[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/ZTIF1v1YGwGePEvVO-qyfnmLL5t0N3KG"
sepolia = "https://sepolia.infura.io/v3/d670ac7f22c94d45a4a8729e2daf865a"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
